# Setup
title:               Anirudh Dash
tagline:             "what's in a name?"
description:         "THOROUGH-1864"
url:                 https://dash-anirudh.github.io
baseurl:             ""
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              "Anirudh Dash"
  url:               https://github.com/dash-anirudh/
  email:             anirudh.dash@yahoo.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             01.07.03
google_analytics_id: #UA-XXXX-Y
